name: Basic workflow that attempts to build the app to ensure that nothing breaks
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event_name == 'push'
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          distribution: "zulu"
          java-version: "11"
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.3.x"
          channel: "stable" # or: 'beta' or 'master'
      - run: flutter pub get
      - run: flutter build apk --debug

  buildDev:
    runs-on: ubuntu-latest
    needs: build
    if: github.event_name == 'push' && github.ref == 'refs/heads/develop'
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          distribution: "zulu"
          java-version: "11"
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.3.x"
          channel: "stable" # or: 'beta' or 'master'
      - run: flutter pub get
      - run: flutter build apk --debug

  buildProd:
    runs-on: ubuntu-latest
    needs: build
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          distribution: "zulu"
          java-version: "11"
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.3.x"
          channel: "stable" # or: 'beta' or 'master'
      - run: flutter pub get
#      - run: flutter build apk
